import os
import json
import google.generativeai as genai

class SemanticOptogeneticEncoder:
    """
    Leverages the Gemini API to translate complex human objectives 
    into precise, multi-channel optical stimulation patterns.
    """
    def __init__(self):
        genai.configure(api_key=os.environ["GEMINI_API_KEY"])
        # Utilizing the core model for complex reasoning and JSON output
        self.model = genai.GenerativeModel('gemini-3.1-pro')

    def generate_stimulus_from_intent(self, user_intent: str) -> dict:
        """
        Asks Gemini to design a specific firing protocol for the ChrimsonR and ChR2 
        opsins to encode the user's conceptual task into the biological reservoir.
        """
        prompt = f"""
        You are the digital orchestration layer of a bio-digital supercomputer.
        The user has provided the following computational objective for the neural organoid:
        "{user_intent}"
        
        Design an optogenetic pulse sequence to encode this task. The reservoir has two input channels:
        1. 470nm (ChR2) - Excitatory, fast kinetics (0-50Hz)
        2. 590nm (ChrimsonR) - Excitatory, deep tissue penetration (0-20Hz)
        
        Return ONLY a valid JSON object containing the frequency arrays and pulse widths.
        """
        
        response = self.model.generate_content(prompt)
        # Parse the JSON generated by Gemini into an actionable hardware config
        return json.loads(response.text)

# Example Execution:
# encoder = SemanticOptogeneticEncoder()
# biological_machine_code = encoder.generate_stimulus_from_intent(
#     "Establish a fading memory state capable of classifying nonlinear weather data."
# )
